spring.application.name=AiAgent


spring.datasource.url=jdbc:postgresql://localhost:5432/HelpDesk
spring.datasource.username=postgres
spring.datasource.password=varun
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web.client=TRACE
logging.level.org.springframework.web.reactive.function.client=TRACE
logging.level.org.springframework.web=DEBUG

spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.options.model=nvidia/nemotron-3-ultra-550b-a55b:free

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.openai.headers.HTTP-Referer=http://localhost:8080
spring.ai.openai.headers.X-Title=AiAgent